app = "adc-mass-matcher"
[build]
  dockerfile = "Dockerfile"
[[services]]
  internal_port = 8501
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
